# Generated by Django 2.1 on 2018-11-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='unique_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True),
        ),
    ]
